/*시퀀스 캐시 초기화 코드 모음. 아래 ALTER SEQUENCE 쿼리목록 전부 실행하면 됨*/

--시퀀스 변경문 생성 쿼리. 개발중 새로운 시퀀스 추가시 아래 쿼리 실행 후 결과목록에서 필요한 쿼리 추가해주면 됨
SELECT 'ALTER SEQUENCE ' || sequence_name || ' NOCACHE;' FROM user_sequences;

SELECT sequence_name, cache_size FROM user_sequences; --시퀀스 캐시 크기 확인 쿼리. 실행해서 변경 잘 됐는지 확인
 commit;
/*여기부터 시퀀스 캐시 크기 변경문*/
ALTER SEQUENCE ACCOUNT_NO_SEQ NOCACHE;
ALTER SEQUENCE ACCOUNT_SEQ NOCACHE;
ALTER SEQUENCE CARD_NO_SEQ NOCACHE;
ALTER SEQUENCE CHEATREPORT_NO_SEQ NOCACHE;
ALTER SEQUENCE GIFT_NO_SEQ NOCACHE;
ALTER SEQUENCE HIBERNATE_SEQUENCE NOCACHE;
ALTER SEQUENCE LISTING_SEQ NOCACHE;
ALTER SEQUENCE LOAN_NO_SEQ NOCACHE;
ALTER SEQUENCE LOGINHIS_SEQ NOCACHE;
ALTER SEQUENCE NOTICE_SEQ NOCACHE;
ALTER SEQUENCE POINT_HISTORY_SEQ NOCACHE;
ALTER SEQUENCE QUIZ_NO_SEQ NOCACHE;
ALTER SEQUENCE QUIZ_RESULT_NO_SEQ NOCACHE;
ALTER SEQUENCE QUIZ_RESULT_SEQ NOCACHE;
ALTER SEQUENCE QUIZ_SEQ NOCACHE;
ALTER SEQUENCE SEQ_ACCOUNT_ID NOCACHE;
ALTER SEQUENCE STOCKHOLDING_SEQ NOCACHE;
ALTER SEQUENCE STOCK_ID_SEQ NOCACHE;
ALTER SEQUENCE STOCK_TRANSACTION_SEQ NOCACHE;
ALTER SEQUENCE TRANSACTION_SEQ NOCACHE;
ALTER SEQUENCE USER_NO_SEQ NOCACHE;