INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (1,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q1. 신용카드는 대출이 가능하다. ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (2,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q2. 예금은 원금을 보장한다. ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (3,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q3. 대출 금리는 경제 상황에 따라 변할 수 있다. ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (4,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q4. 적금은 정해진 기간 동안 돈을 맡기는 방식이다.  ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (5,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q5. 보험금은 사고가 발생해야 받는다. ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (6,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q6. 신용 점수는 대출을 받을 때 중요한 요소다.  ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (7,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q7. 카드 대출은 높은 금리가 적용될 수 있다.  ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (8,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q8. 상속세는 상속을 받을 때 부과된다. ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (9,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q9. 예금 보험공사는 예금자의 돈을 보호한다. ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (10,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q10. 은행 대출은 신용 평가를 바탕으로 승인된다. ','금융', SYSTIMESTAMP);