INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (1,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q1. 신용카드는 대출이 가능하다. ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (2,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q2. 예금은 원금을 보장한다. ','금융', SYSTIMESTAMP);

INSERT INTO QUIZ (QUIZ_ID, CORRECT_ANSWER, LAST_ATTEMPT_DATE, POINTS, QUESTION, CATEGORY, CREATED_DATE) 
VALUES (3,'O', TO_TIMESTAMP('2025-01-18 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 100, 'Q3. 대출 금리는 경제 상황에 따라 변할 수 있다. ','금융', SYSTIMESTAMP);

