select * from stock;

drop table stock;

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (1, 'Apple Inc.', 'AAPL', 'Technology', 169000, 210000, 16000000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (2, 'Microsoft Corp.', 'MSFT', 'Technology', 305000, 330000, 12000000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (3, 'Procter and Gamble', 'PG', 'Consumer Goods', 180000, 195000, 10000000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (4, 'Coca-Cola Co.', 'KO', 'Consumer Goods', 75000, 83000, 9500000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (5, 'JPMorgan Chase', 'JPM', 'Finance', 200000, 220000, 14000000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (6, 'Goldman Sachs', 'GS', 'Finance', 340000, 360000, 6000000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (7, 'Johnson and Johnson', 'JNJ', 'HealthCare', 170000, 190000, 8000000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (8, 'Pfizer Inc.', 'PFE', 'HealthCare', 50000, 55000, 20000000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (9, 'ExxonMobil Corp.', 'XOM', 'Energy', 95000, 105000, 11000000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (10, 'Chevron Corp.', 'CVX', 'Energy', 130000, 145000, 9000000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (11, 'Walmart Inc.', 'WMT', 'Retail', 170000, 185000, 13000000,  1, SYSDATE);

INSERT INTO STOCK (STOCK_ID, COMPANY_NAME, TICKER_SYMBOL, SECTOR, INITIAL_PRICE, CURRENT_PRICE, TOTAL_SHARES,  IS_ACTIVE, CREATED_DATE) 
VALUES (12, 'Amazon.com Inc.', 'AMZN', 'Retail', 300000, 325000, 15000000,  1, SYSDATE);

commit;