spring.messages.encoding=UTF-8
#주석을 살릴 수 있을 것인가? 실패ㅠ
spring.application.name=Spike

#tomcat port number
server.port=8070

#oracle connect
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521:xe
spring.datasource.username=spike
spring.datasource.password=12345

<<<<<<< HEAD
#view page path(Ã«Â·Â°Ã«Â¦Â¬Ã¬Â¡Â¸Ã«Â¸Â ÃªÂ²Â½Ã«Â¡Â-> Ã«Â·Â°Ã­ÂÂÃ¬ÂÂ´Ã¬Â§Â ÃªÂ²Â½Ã«Â¡Â)
spring.mvc.view.prefix=/WEB-INF/views/
#view page Ã­ÂÂÃ¬ÂÂ¥Ã¬ÂÂ
spring.mvc.view.suffix=.jsp

#mybatis Ã¬ÂÂ¤Ã¬Â Â
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:com/spike/mappers/**/*.xml

#table create/update => createÃ«ÂÂ ÃªÂ¸Â°Ã¬Â¡Â´Ã­ÂÂÃ¬ÂÂ´Ã«Â¸ÂÃ¬ÂÂ Ã¬ÂÂ­Ã¬Â ÂÃ­ÂÂÃªÂ³Â  Ã«ÂÂ¤Ã¬ÂÂ Ã¬ÂÂÃ¬ÂÂ±, updateÃ«ÂÂ Ã«Â³ÂÃªÂ²Â½Ã«ÂÂ Ã«Â¶ÂÃ«Â¶ÂÃ«Â§Â Ã«Â°ÂÃ¬ÂÂ
spring.jpa.hibernate.ddl-auto=update
#DDL Ã«ÂÂ°Ã¬ÂÂ´Ã­ÂÂ° Ã¬Â ÂÃ¬ÂÂÃ¬ÂÂ´Ã¬ÂÂ¸ CREATE, alter, drop, truncate(Ã¬Â ÂÃ¬Â²Â´ Ã«Â ÂÃ¬Â½ÂÃ«ÂÂ Ã¬ÂÂ­Ã¬Â ÂÃ«Â¬Â¸) , rename(Ã­ÂÂÃ¬ÂÂ´Ã«Â¸ÂÃ«ÂªÂ,Ã¬Â»Â¬Ã«ÂÂ¼Ã«ÂªÂ Ã«Â³ÂÃªÂ²Â½Ã«Â¬Â¸)Ã«Â¬Â¸ Ã¬ÂÂ¬Ã¬ÂÂ©Ã¬ÂÂ Ã¬ÂÂÃ«ÂÂÃ¬ÂÂ¼Ã«Â¡Â Ã¬ÂÂÃ¬ÂÂ±Ã­ÂÂÃªÂ³Â  Ã¬ÂÂ¤Ã­ÂÂÃ­ÂÂÃ«ÂÂÃ«Â¡Â
#Ã¬ÂÂ¤Ã¬Â ÂÃ­ÂÂÃ«ÂÂ Ã¬ÂÂµÃ¬ÂÂ
spring.jpa.generate-ddl=true
#SQL SHOW
spring.jpa.show-sql=true
#Ã«ÂÂ°Ã¬ÂÂ´Ã­ÂÂ° Ã«Â²Â Ã¬ÂÂ´Ã¬ÂÂ¤ Ã¬ÂÂ Ã­ÂÂ
spring.jpa.database=oracle
#log
logging.level.org.hibernate=info
#oracle Ã¬ÂÂÃ¬ÂÂ¸ Ã¬Â ÂÃ«Â³Â´
=======
#view page path
spring.mvc.view.prefix=/WEB-INF/views/
#view page ��
spring.mvc.view.suffix=.jsp

#mybatis�
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:com/spike/mappers/**/*.xml


#table create/update��
spring.jpa.hibernate.ddl-auto=update
#DDL CREATE, alter, drop, truncate, rename�
spring.jpa.generate-ddl=true
#SQL SHOW
spring.jpa.show-sql=true
#DB��
spring.jpa.database=oracle
#log
logging.level.org.hibernate=info
#oracle
>>>>>>> develop
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

