spring.application.name=Spike

# Tomcat port number
server.port=8070

# Oracle connect
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521:xe
spring.datasource.username=spike
spring.datasource.password=12345

# View page 설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# MyBatis 설정
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:com/spike/mappers/**/*.xml

# Hibernate DDL 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

# Oracle database 설정
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# Logging 설정
logging.level.org.hibernate=info

# 파일 업로드 설정
spring.servlet.multipart.max-file-size=100MB     
spring.servlet.multipart.max-request-size=100MB   
